// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Test.Model
{
    public partial class SessionSlotData
    {
        public int Id { get; set; }
        public string SessionSlotGuid { get; set; }
        public string Key { get; set; }
        public byte[] Data { get; set; }
        public DateTime ModifiedAtUtc { get; set; }

        public virtual SessionSlot SessionSlotGuidNavigation { get; set; }
    }
}